### ISSUE TITLE
能否对接一下shamrock呢

### ISSUE THREAD

**Issue by aknyzsd** [ziru-w/nonebot_plugin_addFriend#10]
gocq基本暴毙了，现在正在尝试用shamrock，shamrock虽然写了说有加好友/群的接口但是接口貌似并不兼容qwq

**Comment by ziru-w** [comment]
你可以学一下写一写，加油
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/0055dbe6-5b8d-48e9-8c8c-90eef680a7be)
说起来我还用着qsign和gocq，版本.88

**Comment by aknyzsd** [comment]
> 你可以学一下写一写，加油
> ![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/0055dbe6-5b8d-48e9-8c8c-90eef680a7be)
> 说起来我还用着qsign和gocq，版本.88

好像不是接口不兼容，而是服务端和主机不能直接通讯，好像需要转码

**Comment by aknyzsd** [comment]
> 你可以学一下写一写，加油
> ![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/0055dbe6-5b8d-48e9-8c8c-90eef680a7be)
> 说起来我还用着qsign和gocq，版本.88

.88版本数据大了就会崩溃（例如图片语音或者视频）
看不明白了插件显示running complete，但是shamrock端没有响应日志如果接口不互通为何nb端可以收到信息呢qwq![Screenshot_20240102_232541_com.wujie.connect.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/70fae592-f6a8-4d41-b24a-894e11714626)![Screenshot_20240102_232518_com.wujie.connect.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/2d1d72d9-1700-4c1e-8bad-a324e6e05fa6)

**Comment by ziru-w** [comment]
不知道啊，我没接触过shamrock，我还是崩溃了就重启，这两天准备写一个自动检测重启，然后就这样得过且过



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月2日(周二) 晚上11:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能否对接一下shamrock呢 (Issue #10)




  
你可以学一下写一写，加油
 image.png (view on web)
 说起来我还用着qsign和gocq，版本.88
  
.88版本数据大了就会崩溃（例如图片语音或者视频）
 看不明白了插件显示running complete，但是shamrock端没有响应日志如果接口不互通为何nb端可以收到信息呢qwqScreenshot_20240102_232541_com.wujie.connect.jpg (view on web)Screenshot_20240102_232518_com.wujie.connect.jpg (view on web)

**Comment by aknyzsd** [comment]
> 不知道啊，我没接触过shamrock，我还是崩溃了就重启，这两天准备写一个自动检测重启，然后就这样得过且过
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年1月2日(周二) 晚上11:31
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [ziru-w/nonebot_plugin_addFriend] 能否对接一下shamrock呢 (Issue #10)
> 
> 
> 
> 
>   
> 你可以学一下写一写，加油
>  image.png (view on web)
>  说起来我还用着qsign和gocq，版本.88
>   
> .88版本数据大了就会崩溃（例如图片语音或者视频）
>  看不明白了插件显示running complete，但是shamrock端没有响应日志如果接口不互通为何nb端可以收到信息呢qwqScreenshot_20240102_232541_com.wujie.connect.jpg (view on web)Screenshot_20240102_232518_com.wujie.connect.jpg (view on web)
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

加油吧佬
要是gocq能得过且过能不能也让我抄抄（doge）
我是gocq实在过不下去了才转的shamrock

**Comment by aknyzsd** [comment]
佬能不能救一下，做不明白了，根据shamrock的文档上写的，应该是可以和gocq无痛迁移的，接口完全一样但是并然，我在想是不是跟bot和shamrock不在同一个系统环境下有关系，毫无思路qwq
以下是运行日志，在53分11秒末尾显示addfriend运行完成好像是
![Screenshot_20240124_165454_com.wujie.connect.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/4b2a617b-a0ef-4a7f-940b-146381bce234)![Screenshot_20240124_165654_com.wujie.connect.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/02ce6a0d-7465-45cd-ab26-4da2c0995826)

**Comment by ziru-w** [comment]
这不也没报错，啥问题呀

**Comment by ziru-w** [comment]
说起来我没写自动重启，直接用了系统自带的定时任务让qsign和gocq每隔1小时重启一次，运行了估计1周了，状况稳定
![)F2}L$I$KZX3EK7N(05$2CJ](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/d3ae73ca-0e1b-4ef5-8d1f-75bc4f3a3dbf)

**Comment by aknyzsd** [comment]
> 这不也没报错，啥问题呀
> 

但是加群请求并没有被通过，我也没有收到bot相关报告，通过查看加群命令显示为空

**Comment by aknyzsd** [comment]
> 说起来我没写自动重启，直接用了系统自带的定时任务让qsign和gocq每隔1小时重启一次，运行了估计1周了，状况稳定
> ![)F2}L$I$KZX3EK7N(05$2CJ](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/d3ae73ca-0e1b-4ef5-8d1f-75bc4f3a3dbf)
> 

我这边3分钟崩一次qwq

**Comment by ziru-w** [comment]
你可以在这里加个print("其他类型")测试下是不是类型判断出错
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/bbb398cb-3624-45de-9040-0e8cf9f91317)
如果输出了"其他类型"那么可以修改isinstance(event,FriendRequestEvent)为event.request_type=="friend"，isinstance(event,GroupRequestEvent)为event.request_type=="group"试试
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/3c2ebcba-1bc5-42e7-a0bb-f3a78700b694)

**Comment by aknyzsd** [comment]
彳亍，我去试试

**Comment by aknyzsd** [comment]
修改后出现新的报错![Screenshot_20240126_011704_com.wujie.connect.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/d3433685-ea17-4174-a55f-f6bc44582573)

**Comment by aknyzsd** [comment]
貌似不能这么搞，但是雀食被判定为无效信息了

**Comment by ziru-w** [comment]
你怎么能这么改，我的天

**Comment by ziru-w** [comment]
话说回来只改print("其他类型")时，输出其他类型了吗

**Comment by aknyzsd** [comment]
雀食判定为其他类型了

**Comment by ziru-w** [comment]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/1d70a8df-bb8f-4df1-b9b8-7c549b52d170)
这样的

**Comment by ziru-w** [comment]
isinstance()可是个二参函数，你把布尔类型的关系式代进去肯定会报错

**Comment by aknyzsd** [comment]
我在想能不能print出收到的消息，我怀疑是不是shamrock写的时候加了点东西

**Comment by ziru-w** [comment]
isinstance()是比较数据类型的函数，这里可能类型发生了变化，比较结果为false了，你改成我给你发的图片试试，话说回来我给你的是整个，你咋只改了括号里的，event.request_type=="friend"就已经是单独的判断句了

**Comment by ziru-w** [comment]
快试试，说不定会有效

**Comment by aknyzsd** [comment]
好像有效了，但是触发了祖传bug
![Screenshot_20240126_013220_com.wujie.connect.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/ba86d878-6058-4cc3-ae45-5d3a37826a97)

**Comment by ziru-w** [comment]
咂舌，应该是这个接口没实现，不知道改了这个还有几个
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/48d627c2-2b5e-44f3-8734-3e939047b66e)

**Comment by aknyzsd** [comment]
官方说实现了的，倒是之前在gocq也出过这个报错（怪）

**Comment by ziru-w** [comment]
这段代码的作用是用来判断该群是否已加入，我想想怎么回避，有了
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/0a56e3c8-9eab-40b0-b51b-562a25880bac)
把addInfo=await bot.get_group_info(group_id=int(id),no_cache=True)改为
        try:
            addInfo=await bot.get_group_info(group_id=int(id),no_cache=True)
        except Exception as res:
            print("nonebot_plugin_addFriend/__init__.py61行\n",res)
            addInfo={"member_count":0,"max_member_count":0,"group_name":"略过","group_id":event.group_id}

**Comment by ziru-w** [comment]
注意缩进

**Comment by aknyzsd** [comment]
翻了翻文档，貌似支持，怪诶![Screenshot_20240126_014711_com.microsoft.emmx.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/a6e7dbb5-5e13-4527-923d-bef998c9fa38)![Screenshot_20240126_014806_com.microsoft.emmx.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/58a7ae85-6260-48f9-b0e8-a467c8e931b0)

**Comment by ziru-w** [comment]
可能是qq一些协议改了吧，没加群前没法用这个旧接口查信息了

**Comment by ziru-w** [comment]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/f5264d9c-e3dd-435a-b13a-4a384234f3d7)
刚才那张图片有点问题，是这张

**Comment by ziru-w** [comment]
刚才粘贴到58行去了

**Comment by aknyzsd** [comment]
qwq
![Screenshot_20240126_020906_com.wujie.connect.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/a6fa98f2-3b85-4d53-8b3c-efd6af6f41e4)

**Comment by ziru-w** [comment]
event.get_user_id()改为event.user_id，同时输出下这个看看event类型
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/7a8cdd8f-4654-41ab-b4dc-bf1330b56271)

        print(type(event))
        msg='群号{}，{}{}{}\n时间:{}'.format(id,event.user_id,notice_msg,event.comment,time)

**Comment by ziru-w** [comment]
直接复制这个就好，他可能在这个事件里没有实现event.get_user_id()这个接口吧

**Comment by ziru-w** [comment]
可能这次就没问题了，有问题也该睡了

**Comment by aknyzsd** [comment]
啊这.....
![Screenshot_20240126_023024_com.wujie.connect.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/92c0a2b4-8ed7-41e5-b29f-1a420779d6ce)

**Comment by aknyzsd** [comment]
有user_id啊qwq
![Screenshot_20240126_122323_com.microsoft.emmx.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/9c2157e4-6d85-4926-8912-eb0f3d88a231)

**Comment by ziru-w** [comment]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/ef7910a5-a923-4e30-b996-9b6233f6250c)
这样把在开头加个comment="略过"，然后再把event.comment全替换成comment就好

**Comment by aknyzsd** [comment]
新的.....![Screenshot_20240126_133604_com.wujie.connect.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/5c70134e-e6c2-43ae-a754-2274710abd59)

**Comment by ziru-w** [comment]
这就是最后一个环节同意加入了，这个事件真的有被实现吗，怎么函数没一个能用。
把await event.approve(bot)改为await bot.set_friend_add_request(flag=event.flag,approve=True)
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/f8220369-9c90-4612-a52b-a169a26f7221)

**Comment by ziru-w** [comment]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/7177bef3-b1f8-4d7a-b05f-35ae4dce74a8)
刚才的有点问题，没区分群聊好友，这样

**Comment by aknyzsd** [comment]
这是...接口错误？![Screenshot_20240126_141302_com.wujie.connect.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/e1acb35f-fe46-4100-b160-cf5483c8dc7b)

**Comment by ziru-w** [comment]
if autoType=='friend':
            await bot.set_friend_add_request(flag=event.flag,approve=True)
        else:
            await bot.set_group_add_request(flag=event.flag,sub_type=event.sub_type,approve=True)

**Comment by ziru-w** [comment]
加上这个sub_type=event.sub_type应该就好了

**Comment by aknyzsd** [comment]
能用辣，感谢带佬

**Comment by ziru-w** [comment]
说起来一开始忘了进行类型转换试试，就像这样说不定后边啥也不用改了
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/9b9e0464-91b4-4284-8f08-c373248d8c9f)

**Comment by ziru-w** [comment]
刚才玩英雄杀已经丝血反杀了，结果一个操作失误被拿走了虎符，真是的，难顶

**Comment by aknyzsd** [comment]
> 说起来一开始忘了进行类型转换试试，就像这样说不定后边啥也不用改了
> ![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/9b9e0464-91b4-4284-8f08-c373248d8c9f)
> 

啊这，容我有空试试去

**Comment by aknyzsd** [comment]
还没改呢，就出了新的bug（可能？）![Screenshot_20240126_215539_com.wujie.connect.jpg](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/80686c6e-bcbe-4445-9faf-3290a45e1c56)

**Comment by ziru-w** [comment]
这段报错的意思是查无请求，容器里没找到这个申请，不清楚什么问题

**Comment by aknyzsd** [comment]
看起来不行.....
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/95bf0093-aacf-45c5-8111-fce43e890108)


> 说起来一开始忘了进行类型转换试试，就像这样说不定后边啥也不用改了 ![image](https://private-user-images.githubusercontent.com/77319678/299929403-9b9e0464-91b4-4284-8f08-c373248d8c9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzA2OTYsIm5iZiI6MTcwNjMzMDM5NiwicGF0aCI6Ii83NzMxOTY3OC8yOTk5Mjk0MDMtOWI5ZTA0NjQtOTFiNC00Mjg0LThmMDgtYzM3MzI0OGQ4YzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA0Mzk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOGE4YWVlYmJiODgzZWJkOGRlMGJlYTgzMDMwY2NhYjBjYzcyNTM2YjgyN2ZmYmE5YWMwNDc4MDk2MGUwMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uNNjlFVep4lgAQ7Mg7dJhFM5Jqj7B5jG7tT73Gw5hTw)

**Comment by aknyzsd** [comment]
对了，能问下都是哪几个接口有问题着不，我去拍shamrock的issue上

**Comment by ziru-w** [comment]
总的来说就是请求事件未能自动转为群请求事件和好友请求事件，以此之前gocq上群请求事件的部分属性和接口不能使用，如comment，approve()，get_user_id()，此外bot.get_group_info()请求出错

**Comment by ziru-w** [comment]
悲，上次修手机的把电池粘的太紧了，我撬电池时忘了屏幕线了，结果把屏幕线好像摁断

**Comment by ziru-w** [comment]
刚给你说完，就又不稳定了，还是得迁移到shamrock

**Comment by ziru-w** [comment]
你用的哪个模拟器呀

**Comment by aknyzsd** [comment]
> 你用的哪个模拟器呀
> 

MuMu是最理想的

**Comment by aknyzsd** [comment]
> 你用的哪个模拟器呀
> 

要不加个q，回来联系方便点2816878214

**Comment by ziru-w** [comment]
已加
