### ISSUE TITLE
每次私聊bot发送命令的时候报错

### ISSUE THREAD

**Issue by linword** [ziru-w/nonebot_plugin_addFriend#2]
![image](https://user-images.githubusercontent.com/43131361/183276460-8a0aa9f9-2b7b-40d0-8aef-632e6fdabe20.png)
辛苦大佬看下，群聊发送命令就没问题

**Comment by linword** [comment]
谢谢大佬，问题已经解决了，更新了版本，对比了发现，`config.json`文件内容是上一个版本生成的，删了重新生成了，这个有没有考虑把配置项让用户自己在`.env.*`中配置呢？感觉就不会出现我这个`config.json`内容的问题，个人拙见，对python也不是很懂，辛苦大佬解答

**Comment by ziru-w** [comment]
1.其实config.json也是可以手动配置的，我忘记在文档里提示更新版本需要手动更新config.json了。
没有更新的话都是一样的，在.env.*中配置也会出同样错。
2.至于.env.*，感觉会导致它看起来有点乱，而且我不熟悉对.env.*的写入和重新载入。没有时间搞这个，时间愈发紧张。
3.不过其实在.env.*中配置也挺好的，机器人所有配置都在一个地方，不用来回找了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ziru-w/nonebot_plugin_addFriend"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月7日(星期天) 中午1:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [ziru-w/nonebot_plugin_addFriend] 每次私聊bot发送命令的时候报错 (Issue #2)





 
谢谢大佬，问题已经解决了，更新了版本，对比了发现，config.json文件内容是上一个版本生成的，删了重新生成了，这个有没有考虑把配置项让用户自己在.env.*中配置呢？感觉就不会出现我这个config.json内容的问题，个人拙见，对python也不是很懂，辛苦大佬解答

**Comment by linword** [comment]
嗯嗯，看大佬自己有空没空和有想法没想法了，还有一个问题是这个插件使用httpx的版本是0.22.0好像？我也不清楚，pip install的时候会下载httpx，但是另一个插件要求的是httpx版本>=0.23.0，这个我用0.23.0会有影响嘛？

**Comment by ziru-w** [comment]
可能会有，也可能没有，这看在插件中调用的方法或对象在两个版本httpx中传参方式是否有区别，是否存在。
如果有影响，可以在utils.py里删掉from nonebot_plugin_txt2img import Txt2Img，
把函数async def parseMsg(commandText,resMsg,font_size = 32,isText=1)
的函数体删为：
async def parseMsg(commandText,resMsg,font_size = 32,isText=1):
&nbsp; &nbsp; &nbsp; &nbsp;return resMsg








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月7日(星期天) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ziru-w/nonebot_plugin_addFriend] 每次私聊bot发送命令的时候报错 (Issue #2)





 
嗯嗯，看大佬自己有空没空和有想法没想法了，还有一个问题是这个插件使用httpx的版本是0.22.0好像？我也不清楚，pip install的时候会下载httpx，但是另一个插件要求的是httpx版本&gt;=0.23.0，这个我用0.23.0会有影响嘛？

**Comment by ziru-w** [comment]
> ![image](https://user-images.githubusercontent.com/43131361/183276460-8a0aa9f9-2b7b-40d0-8aef-632e6fdabe20.png) 辛苦大佬看下，群聊发送命令就没问题

这个是是否转发私聊的开关，旧版config.json没有这个个键

**Comment by ziru-w** [comment]
> 可能会有，也可能没有，这看在插件中调用的方法或对象在两个版本httpx中传参方式是否有区别，是否存在。 如果有影响，可以在utils.py里删掉from nonebot_plugin_txt2img import Txt2Img， 把函数async def parseMsg(commandText,resMsg,font_size = 32,isText=1) 的函数体删为： 
async def parseMsg(commandText,resMsg,font_size = 32,isText=1): 
          return resMsg

httpx是文字转图片插件中导入的依赖，有问题直接删就行，我感觉是没有问题...，但也可能有问题，nonebot_plugin_txt2img作者就用了个AsyncClient()，没用过这个函数，不能肯定有没问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年8月7日(星期天) 下午3:57 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [ziru-w/nonebot_plugin_addFriend] 每次私聊bot发送命令的时候报错 (Issue #2) 嗯嗯，看大佬自己有空没空和有想法没想法了，还有一个问题是这个插件使用httpx的版本是0.22.0好像？我也不清楚，pip install的时候会下载httpx，但是另一个插件要求的是httpx版本&gt;=0.23.0，这个我用0.23.0会有影响嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

**Comment by linword** [comment]
好的，感谢
