### ISSUE TITLE
指令解释不清

### ISSUE THREAD

**Issue by Reversedeer** [ziru-w/nonebot_plugin_addFriend#3]
这个指令解释的太令人费解了 
到现在还不懂1和0到底代表什么，什么情况下是自动同意请求，什么情况下是手动指令同意请求
建议用md格式把文档说明优化一下，太乱了

**Comment by ziru-w** [comment]
先等等，再等几天就考完试了，到时候直接重构

**Comment by ziru-w** [comment]
对了，1应该是自动同意

**Comment by Reversedeer** [comment]
自行摸清楚了qwq，确实应该优化一下
config.json文件看着就头大 : /
