### ISSUE TITLE
没有修改任何设置，但是未通过验证消息，已拒绝 

### ISSUE THREAD

**Issue by aknyzsd** [ziru-w/nonebot_plugin_addFriend#4]
按照默认配置项设置启动nb，无论是否开启自动同意全部为未通过验证消息，已拒绝（没有任何报错），是我有哪里还需要改吗（萌新）

**Comment by ziru-w** [comment]
自动同意全部后应该是这样![image](https://user-images.githubusercontent.com/77319678/214471915-5461f471-483b-44cb-86f1-0089d0c7a8de.png)
你打开配置文件瞅瞅，应该没问题呀

**Comment by aknyzsd** [comment]
过程大概是这样的
心の勇敢烧麦 11:34:47
重载成功:
{'agreeAutoApprove': {'friend': 1, 'group': 1}, 'maxNum': 5, 'maxViewNum': 20, 'recipientList': ['2816878214'], 'groupMemberNumNoticeList': [], 'forwardSet': 1, 'blackDict': {'friend': {'text': [], 'id': []}, 'group': {'text': ['通知'], 'id': []}, 'forward': {}}, 'warnDict': {'friend': {'text': [], 'id': []}, 'group': {'text': ['联谊'], 'id': []}, 'forward': {}}, 'allowAddFriednText': '', 'botNa

心の勇敢烧麦 11:35:29
1545126956请求添加好友,验证消息为我是牛牛三号
时间:2023-01-25 11:35:30.558179
未通过验证消息,已拒绝

**Comment by ziru-w** [comment]
你啥时候下载的插件，这好像是暑假时的版本，我翻翻历史记录。
你可以更新一下，更新时对着改一下config.json或者删了重新生成

**Comment by ziru-w** [comment]
我明白了，之前文档没改，你是不是直接复制文档里的那个文档里的那段config结构了

**Comment by aknyzsd** [comment]
这个是默认生成的我用nb直接从bot文件夹下装的，可能是这个原因导致版本不对？

**Comment by ziru-w** [comment]
> 这个是默认生成的我用nb直接从bot文件夹下装的，可能是这个原因导致版本不对？


不用想太多，再装一次就行

**Comment by aknyzsd** [comment]
重装过了，版本号2.4.4，结果依然是已拒绝

**Comment by ziru-w** [comment]
手动修改一下config.json
{
  "agreeAutoApprove": { "friend": 1, "group": 1 },
  "numControl": { "maxNum": 10, "time": 2, "unit": "h" },
  "maxViewNum": 20,
  "recipientList": ["你的qq"],
  "forwardSet": 1,
  "blackDict": {
    "friend": { "text": [], "id": [] },
    "group": { "text": ["通知"], "id": [] },
    "forward": {}
  },
  "warnDict": {
    "friend": { "text": [], "id": [] },
    "group": { "text": ["联谊"], "id": [] },
    "forward": {}
  },
  "allowAddFriednText": [],
  "botName": "我",
  "friend_msg": {
    "notice_msg": "请求添加好友,验证消息为",
    "welcome_msg": "我未知的的朋友啊，很高兴你添加我为qq好友哦！\n同时，如果有疑问，可以发送/help哦"
  },
  "group_msg": {
    "notice_msg": "发送群邀请,验证消息为",
    "welcome_msg": "我亲爱的的朋友啊，很高兴你邀请我哦！"
  },
  "statusDict": {
    "blackDict": {
      "friend": { "status": "拉黑Q类,已拒绝,仅作提示" },
      "group": { "status": "拉黑群类,已拒绝,仅作提示" }
    },
    "warnDict": {
      "friend": { "status": "警告Q类,手动同意,是否同意" },
      "group": { "status": "警告群类,手动同意,是否同意" }
    }
  }
}

**Comment by ziru-w** [comment]
> 重装过了，版本号2.4.4，结果依然是已拒绝

config.json没删，新装后检测到存在config.json就不会再生成

**Comment by aknyzsd** [comment]
解决了，谢谢大佬，是我疏忽了
