### ISSUE TITLE
能不能把最大加群数量和加好友数量分开呢owo

### ISSUE THREAD

**Issue by aknyzsd** [ziru-w/nonebot_plugin_addFriend#7]
在bot被频繁封号的艰苦摸索中，发现频繁的加群非常容易被封，但是加好友就弱不少，这里考虑了用多个账号人工同意来解决加群难的问题，但是我在同意申请时插件显示没有此请求，尝试列出申请列表插件反馈是一个[]，是因为有了多个账号的问题嘛？

**Comment by ziru-w** [comment]
有可能是多个账号的问题，
两个次数限制可以分开，改一下代码即可



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 晚上6:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)




 
在bot被频繁封号的艰苦摸索中，发现频繁的加群非常容易被封，但是加好友就弱不少，这里考虑了用多个账号人工同意来解决加群难的问题，但是我在同意申请时插件显示没有此请求，尝试列出申请列表插件反馈是一个[]，是因为有了多个账号的问题嘛？

**Comment by ziru-w** [comment]
对了，查群是/查看加群，要带上群字

**Comment by ziru-w** [comment]
> 对了，查群是/查看加群，要带上群字

唔，估计是这样的。当初也没把两个限制分开，要改的话要修改代码，呜呜呜
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/e12e646d-9ccc-4604-8a25-c968a408c5a4)

**Comment by aknyzsd** [comment]
试了一下，还是这样
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/92531a8b-7cbe-4632-bc17-ac76f377ec1e)

**Comment by aknyzsd** [comment]
怎么改呢qwq

**Comment by ziru-w** [comment]
你看一下requestor.json文件里面有数据没

**Comment by ziru-w** [comment]
还有你把209行换成await addFriend.finish(resMsg)
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/3f938b69-f6fc-4a4d-ba42-f485390d204c)

**Comment by aknyzsd** [comment]
有的

**Comment by aknyzsd** [comment]
换完了，我再试试

**Comment by ziru-w** [comment]
> 换完了，我再试试

我自己测试了一下，找到问题了，类型判断出问题了，加一个这个  ,'查看加群'
![Uploading image.png…]()

**Comment by ziru-w** [comment]
我自己测试了一下，找到问题了，类型判断出问题了，加一个这个 ,'查看加群'
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/57e9bc55-0913-4efb-a5e8-cb690c879ac5)

**Comment by aknyzsd** [comment]
彳亍

**Comment by ziru-w** [comment]
> 彳亍

算了，改这个吧，这才是解决方法
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/312b99b2-8203-47d0-8f32-6fccac227af8)

**Comment by aknyzsd** [comment]
emmm，所以都需要改哪里呢qwq

**Comment by ziru-w** [comment]
这样最开始的同意申请的问题也解决了on_command里的不用改也不能改，只需要把
if '群' in commandText:改为if '群' in argsText:即可
或者改为if '群' in commandText or  '群' in argsText:也行

**Comment by ziru-w** [comment]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/d3c5cba9-cf2f-4bd1-85f6-fd3b02280c02)
对了，还要一个这个就没bug了，argsText=argsText.replace("群","").strip()
看来明天要更新一下

**Comment by aknyzsd** [comment]
那那个自动加群数量怎么设定呢

**Comment by ziru-w** [comment]
明日更新问题：1.群列表里没有群号
2.响应纠正
3.判断类型错误与条件去除
4.增加自动加群数量限制与好友区分
应该就这几条了

**Comment by ziru-w** [comment]
> 那那个自动加群数量怎么设定呢

我明天更新一下就行了

**Comment by aknyzsd** [comment]
那我等佬的好消息，感谢

**Comment by aknyzsd** [comment]
我来催更辣！（doge）

**Comment by ziru-w** [comment]
更新了，你可以看看有什么bug没有？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月12日(周六) 晚上6:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)




 
我来催更辣！（doge）

**Comment by aknyzsd** [comment]
有个小问题可以优化一下嘛举个例子
bot只能识别： 同意加群114514
不能识别 同意加群（空格）114514
和 同意加群”114514“
还有怎么设置最大加群数量捏qwq

**Comment by aknyzsd** [comment]
对了，这个插件的recipientList是和superuser同步的嘛，如果不是可不可以做一下，感觉这样方便一些（感谢大佬）

**Comment by ziru-w** [comment]
这样设置/更改最大加数量群聊 数量，README里有写，
+空格会不生效吗，应该不会吧，奇怪，我看看
&nbsp;


匿名
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月13日(星期天) 凌晨0:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)





 
有个小问题可以优化一下嘛举个例子
 bot只能识别： 同意加群114514
 不能识别 同意加群（空格）114514
 和 同意加群”114514“
 还有怎么设置最大加群数量捏qwq

**Comment by aknyzsd** [comment]
我的问题qwq，输错了输成最大加群数量了qwq（可不可以加一个近似识别qwq）
+空格插件会把空格当作一个值，然后就说找不到这个请求了

**Comment by ziru-w** [comment]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/1126ad47-6a9d-4cc5-bc29-d617d1bb632c)
你在225行下面打个print(QQOrGroupId)看看是什么，我这里是正常的

&nbsp;


匿名
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月13日(星期天) 凌晨0:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)





 
我的问题qwq，输错了输成最大加群数量了qwq（可不可以加一个近似识别qwq）
 +空格插件会把空格当作一个值，然后就说找不到这个请求了

**Comment by ziru-w** [comment]
你如果想同步superuser可以使用编辑器替换功能把在init文件里所有config['recipientList']一键替换为list(get_driver().config.superusers)

**Comment by aknyzsd** [comment]
好的感谢，可以加个近似命令识别嘛？

**Comment by ziru-w** [comment]
> 好的感谢，可以加个近似命令识别嘛？

什么意思

**Comment by aknyzsd** [comment]
比如说
同意添加114514
同意添加群114514之类的也能通过，带空格也能通过之类的

**Comment by aknyzsd** [comment]
有时候背错命令真的很难受qwq

**Comment by ziru-w** [comment]
同意加群/群聊是+群
同意加或者同意加好友是+好友
空格无所谓，首尾空格默认去除了
还有这里面还有个加好友帮助命令

**Comment by aknyzsd** [comment]
目前用了这么多天，没有什么很让人头疼的bug（能不能加一个类似于gocq那种每个账号分别管理的功能，每个账号可能情况不一样，用统一的配置可能会有点麻烦）

**Comment by ziru-w** [comment]
可以倒是可以，也不是很难，配置文件可以以QQ号为索引区分配置，然后实现命令时按触发机器人的QQ取配置，但是好麻烦讷。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月23日(周三) 下午2:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)




 
目前用了这么多天，没有什么很让人头疼的bug（能不能加一个类似于gocq那种每个账号分别管理的功能，每个账号可能情况不一样，用统一的配置可能会有点麻烦）

**Comment by aknyzsd** [comment]
佬做做试试呗，被封号封麻了，真的难受qwq，实在不行加个q请你杯奶茶喝（doge）

**Comment by ziru-w** [comment]
这几天研究生开学有点忙，不知道啥时候能做😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月24日(周四) 晚上7:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)




 
佬做做试试呗，被封号封麻了，真的难受qwq，实在不行加个q请你杯奶茶喝（doge）

**Comment by ziru-w** [comment]
还需要吗，需要的话我做做



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月24日(周四) 晚上7:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)




 
佬做做试试呗，被封号封麻了，真的难受qwq，实在不行加个q请你杯奶茶喝（doge）

**Comment by aknyzsd** [comment]
感谢大佬

**Comment by ziru-w** [comment]
呜呜，点到以前扒拉的分支与删除的git命令，废了好大劲变回原状了，也不知对项目有啥影响没。
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/1f2e7b46-c2e0-46dc-94c1-76761814d5e4)

你看看有没bug，我只测试了少部分功能，原本不准备上传提交到pypi的，顺手提交了

**Comment by aknyzsd** [comment]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/130f3dcd-41b2-4d60-9d44-0b88952cca3f)
重载配置是出现以下报错，不是说自动生成嘛qwq

**Comment by ziru-w** [comment]
已解决，下载新版本或者
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/18c0e24c-07e0-48e8-89cc-a2cb782ec6d1)
这里掉下位置就好了，调换后结果如图

**Comment by aknyzsd** [comment]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/bb01c9ed-a796-4d48-9385-2301fe524d02)
已更改，出现错误，先睡觉吧佬，晚安

**Comment by aknyzsd** [comment]
更改之后确实生成了一个配置好像但是再换一个号又不行了

**Comment by ziru-w** [comment]
啥意思，多发截图😘还有换了一个号用了什么命令发生了什么问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月30日(周三) 晚上11:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)




 
更改之后确实生成了一个配置好像但是再换一个号又不行了

**Comment by aknyzsd** [comment]
就是，从另外一个账号发送重载配置，就又出现了上面的报错

**Comment by ziru-w** [comment]
看不出原因，请发报错截图



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月31日(周四) 中午11:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)




 
就是，从另外一个账号发送重载配置，就又出现了上面的报错

**Comment by ziru-w** [comment]
我只有一个机器人号，测试不了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月31日(周四) 中午11:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)




 
就是，从另外一个账号发送重载配置，就又出现了上面的报错

**Comment by aknyzsd** [comment]
就还是上面那个
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/12b96481-0d63-4812-877a-430ff5b9b3f1)

**Comment by aknyzsd** [comment]
佬你可以删了config文件重新生成一个试试，好像还是不行

**Comment by ziru-w** [comment]
我这里没啥问题
&nbsp;


匿名
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月31日(星期四) 中午1:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)





 
佬你可以删了config文件重新生成一个试试，好像还是不行

**Comment by aknyzsd** [comment]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/87e9cca6-f2c0-4477-be0d-c09fbf6090b0)
还是这个报错，会不会是python版本不兼容啥的，玩不明白了，开始是自己改的感觉自己改的可能不对又更新了一下还是这个问题

**Comment by ziru-w** [comment]
哦，抱歉，我刚才睡着了，原来是这里的错误，不必修了，你应该把这里删了
&nbsp;


匿名
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月31日(星期四) 下午4:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)





 

 还是这个报错，会不会是python版本不兼容啥的，玩不明白了，开始是自己改的感觉自己改的可能不对又更新了一下还是这个问题

**Comment by aknyzsd** [comment]
删掉第377行对嘛？

**Comment by ziru-w** [comment]
> ![image](https://user-images.githubusercontent.com/121467598/264577546-87e9cca6-f2c0-4477-be0d-c09fbf6090b0.png) 还是这个报错，会不会是python版本不兼容啥的，玩不明白了，开始是自己改的感觉自己改的可能不对又更新了一下还是这个问题
你如果想用这个功能的话，就在if config[bot.self_id]['recipientList']==[] or config[bot.self_id]['forwardSet']==0:前面加一行
    check_dict_key_bot_id(config,requestorDict,numDict,bot)#这是用来检测机器人对应配置存在与否与自动创建的函数

**Comment by aknyzsd** [comment]
好的我去试试

**Comment by ziru-w** [comment]
准确的说是从364行删到396行，即把这俩函数删了
这个错误就是转发机器人接收到消息时，发现没这个机器人对应的配置
> 删掉第377行对嘛？

**Comment by aknyzsd** [comment]
> > ![image](https://user-images.githubusercontent.com/121467598/264577546-87e9cca6-f2c0-4477-be0d-c09fbf6090b0.png) 还是这个报错，会不会是python版本不兼容啥的，玩不明白了，开始是自己改的感觉自己改的可能不对又更新了一下还是这个问题
> > 你如果想用这个功能的话，就在if config[bot.self_id]['recipientList']==[] or config[bot.self_id]['forwardSet']==0:前面加一行
> > check_dict_key_bot_id(config,requestorDict,numDict,bot)#这是用来检测机器人对应配置存在与否与自动创建的函数

添加了，可以运行了正在测试，话说这是哪个功能，私聊转发嘛？

**Comment by ziru-w** [comment]
是的

**Comment by aknyzsd** [comment]
嗯...？貌似还添加了通过su直接添加管理的功能，感谢（怎么实现的呢）

**Comment by ziru-w** [comment]
删了就行，这个功能不适用于高强度私聊，我自己用的，其实还有一个配套的发送功能，我一般会给注释掉，这次忘删了

**Comment by ziru-w** [comment]
> 嗯...？貌似还添加了通过su直接添加管理的功能，感谢（怎么实现的呢）

你是指什么

**Comment by aknyzsd** [comment]
> > 嗯...？貌似还添加了通过su直接添加管理的功能，感谢（怎么实现的呢）
> 
> 你是指什么

这次recipientList直接引用的superuser

**Comment by ziru-w** [comment]
事实上每次都引用了前俩个，一样的

**Comment by ziru-w** [comment]
初始化时取了su的前两个，以前说过

**Comment by aknyzsd** [comment]
我又带着bug来辣，因为是功能实现的问题所以没有报错，所有bot貌似使用的依然是一个变量，而且不知道为啥这个插件貌似会触发两次
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/e83cc242-a891-4f60-acc6-e80722899517)
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/bf7ced82-d9f8-4949-8d6d-46ab1f29fccb)
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/e1f9a492-4ab9-4eee-9bfd-a98b48b90a9b)

**Comment by aknyzsd** [comment]
> 我又带着bug来辣，因为是功能实现的问题所以没有报错，所有bot貌似使用的依然是一个变量，而且不知道为啥这个插件貌似会触发两次 ![image](https://user-images.githubusercontent.com/121467598/265268075-e83cc242-a891-4f60-acc6-e80722899517.png) ![image](https://user-images.githubusercontent.com/121467598/265268114-bf7ced82-d9f8-4949-8d6d-46ab1f29fccb.png) ![image](https://user-images.githubusercontent.com/121467598/265268144-e1f9a492-4ab9-4eee-9bfd-a98b48b90a9b.png)

如上所示，当一个账号对多个bot加好友时，不同的bot在超过几次后都显示达到上限，但是为了这个测试今天我bot都没开，不可能说加满了

**Comment by ziru-w** [comment]
私聊转发暂不维护，还有第二个问题不知道，最近比较忙，我没有第二个机器人，不好修

**Comment by ziru-w** [comment]
还有建议看看num.json里的次数

**Comment by ziru-w** [comment]
而且问题表述不是很清晰，不太懂你的意思，建议重新组织语言再问一次

**Comment by aknyzsd** [comment]
"1538459018": {
        "friend": {
            "count": 6,
            "time": "2023-09-03 20:01:42.969353"
        },
        "group": {
            "count": 2,
            "time": "2023-09-03 16:54:43.570354"
        }
    },
    "2126989959": {
        "friend": {
            "count": 6,
            "time": "2023-09-03 20:01:42.969353"
        },
        "group": {
            "count": 2,
            "time": "2023-09-03 16:54:43.570354"
        }
    },
    "2229211807": {
        "friend": {
            "count": 6,
            "time": "2023-09-03 20:01:42.969353"
        },
        "group": {
            "count": 2,
            "time": "2023-09-03 16:54:43.570354"
        }
    },
    "3645192171": {
        "friend": {
            "count": 6,
            "time": "2023-09-03 20:01:42.969353"
        },
        "group": {
            "count": 2,
            "time": "2023-09-03 16:54:43.570354"
        }
    },
    "3081792290": {
        "friend": {
            "count": 6,
            "time": "2023-09-03 20:01:42.969353"
        },
        "group": {
            "count": 2,
            "time": "2023-09-03 16:54:43.570354"
        }
    },
    "2144681263": {
        "friend": {
            "count": 6,
            "time": "2023-09-03 20:01:42.969353"
        },
        "group": {
            "count": 2,
            "time": "2023-09-03 16:54:43.570354"
        }
    },
    "3510881587": {
        "friend": {
            "count": 6,
            "time": "2023-09-03 20:01:42.969353"
        },
        "group": {
            "count": 2,
            "time": "2023-09-03 16:54:43.570354"
        }
    },
    "2909848596": {
        "friend": {
            "count": 6,
            "time": "2023-09-03 20:01:42.969353"
        },
        "group": {
            "count": 2,
            "time": "2023-09-03 16:54:43.570354"
        }
    },
    "2573442978": {
        "friend": {
            "count": 6,
            "time": "2023-09-03 20:01:42.969353"
        },
        "group": {
            "count": 2,
            "time": "2023-09-03 16:54:43.570354"
        }
    },
    "2038994909": {
        "friend": {
            "count": 6,
            "time": "2023-09-03 20:01:42.969353"
        },
        "group": {
            "count": 2,
            "time": "2023-09-03 16:54:43.570354"
        }
    }
}
以上为num里的所有数据为何多个账号的time都是"2023-09-03 20:01:42.969353

**Comment by aknyzsd** [comment]
> 而且问题表述不是很清晰，不太懂你的意思，建议重新组织语言再问一次

问题一：貌似bot在处理加群加好友信息时处理了两次，所以发送了两次不同的数据如图
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/51367715-475d-4474-82ac-076ec00095be)
问题二：虽然区分了不同的设置，但是加群加好友次数并没有隔离，而是统一的。
（并没有私聊转发的问题，那个只是我瞎折腾）

**Comment by ziru-w** [comment]
问题一可能注释掉私聊转发可以解决

**Comment by ziru-w** [comment]
你这机器人不少啊，其实可以把qq号涂一涂，感觉发网上不太好

**Comment by ziru-w** [comment]
你感觉这是实际的数据还是啥

**Comment by ziru-w** [comment]
不怎么能看出来问题，你确定这不是几个qq都加满了，还没到下一个时间周期恢复

**Comment by ziru-w** [comment]
如果是统一的，可真够诡异的

**Comment by aknyzsd** [comment]
问题不大，删除了，明天再去试试，对了这个插件没有对删好友再加有限制吧，我明天删了再加试试不会卡出新的bug吧qwq

**Comment by ziru-w** [comment]
行，我大概知道了，我修一下

**Comment by ziru-w** [comment]
应该修好了，睡了

**Comment by aknyzsd** [comment]
感谢，我先下载一下测试去了，每天给佬反馈

**Comment by ziru-w** [comment]
真是烦呐，新室友11.就睡了，还见不了一点光，而且他这个人有点自我，要是和我后边那个室友就好咯



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月3日(周日) 晚上11:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)




 
感谢，我先下载一下测试去了，每天给佬反馈

**Comment by ziru-w** [comment]
被老师鸽了，这个点恐怕没啥好方向了，生化环材上等211，要不要退学二战计学呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月3日(周日) 晚上11:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)




 
感谢，我先下载一下测试去了，每天给佬反馈

**Comment by aknyzsd** [comment]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/121467598/9321e396-3fb2-4f71-89e5-066e3fe2e108)
发现新的问题，可以通过删除num.config解决
（话说咱以后gocq挂了是不是需要重新做适配）

**Comment by ziru-w** [comment]
更新就行，这个早修过了，时间字符串转格式那里更新后没处理

**Comment by ziru-w** [comment]
gocq挂了是啥意思，风控吗，你可以使用qsign

**Comment by aknyzsd** [comment]
> gocq挂了是啥意思，风控吗，你可以使用qsign

去看看公告吧，停止维护了

**Comment by ziru-w** [comment]
这样吗，好的
&nbsp;


匿名
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月12日(星期四) 晚上11:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ziru-w/nonebot_plugin_addFriend] 能不能把最大加群数量和加好友数量分开呢owo (Issue #7)





  
gocq挂了是啥意思，风控吗，你可以使用qsign
  
去看看公告吧，停止维护了
