### ISSUE TITLE
陌生人发好友请求后valueError报错

### ISSUE THREAD

**Issue by xiaowww3** [ziru-w/nonebot_plugin_addFriend#8]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/84241722/9f39cb40-87e4-4d23-8939-bede03bf17c3)

**Comment by ziru-w** [comment]
好了，重启后再次读入文件后，没格式化引起的，或者说时间间隔函数格式化字符串时匹配字段过短导致的

**Comment by xiaowww3** [comment]
> 好了，重启后再次读入文件后，没格式化引起的，或者说时间间隔函数格式化字符串时匹配字段过短导致的

大佬，那么请问具体怎么解决呢

**Comment by ziru-w** [comment]
害，就是以前写的一个计算时间间隔的函数格式化时间字符串时，少格式化了秒和更小的部分，引起了报错。
从两方面解决了，首先在读文件时把字符串转化为对象了，这样把对象传进去就是正常计算的。然后再函数里也增加了秒的格式化字段，这样即使传进来字符串也不会在报错了。

**Comment by ziru-w** [comment]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/98ad6672-534f-43eb-a7cb-3591b4226679)
翻译：未转化数据剩余

**Comment by ziru-w** [comment]
这个问题可以关了
