### ISSUE TITLE
使用指令不能改动最大数量

### ISSUE THREAD

**Issue by xiaowww3** [ziru-w/nonebot_plugin_addFriend#9]
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/84241722/e9f8091c-a493-47ad-84f7-3d77c55a2ea8)

**Comment by xiaowww3** [comment]
各种格式都试过了

**Comment by ziru-w** [comment]
行，今天晚上看看，你可以先手动修改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月19日(周二) 凌晨2:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 使用指令不能改动最大数量 (Issue #9)




 
各种格式都试过了

**Comment by ziru-w** [comment]
已修复，鉴定为输入命令错误，/更改最大加数量好友 200
注意这里数量和好友中没有加字
此外，200个好友真的没问题吗，感觉容易风控

**Comment by ziru-w** [comment]
哈哈，下次看命令仔细点，忘了可以输入/加好友帮助

**Comment by xiaowww3** [comment]
有加的啊，我是这样输的呀，就随便测试一下的数字



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月19日(周二) 中午11:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 使用指令不能改动最大数量 (Issue #9)




 
已修复，鉴定为输入命令错误，/更改最大加数量好友 200
 注意这里数量和好友中没有加字
 此外，200个好友真的没问题吗，感觉容易风控

**Comment by xiaowww3** [comment]
哦，知道了，还以为是我图发错了，我傻了，没事了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月19日(周二) 中午11:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ziru-w/nonebot_plugin_addFriend] 使用指令不能改动最大数量 (Issue #9)




 
已修复，鉴定为输入命令错误，/更改最大加数量好友 200
 注意这里数量和好友中没有加字
 此外，200个好友真的没问题吗，感觉容易风控

**Comment by ziru-w** [comment]
对了，没有问题后可以点这里关闭
![image](https://github.com/ziru-w/nonebot_plugin_addFriend/assets/77319678/53373381-80af-4182-a595-51b915031673)
